#!/usr/bin/env bash
# transfers a file
if [[ $# < 3 ]]
then echo '0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
elif [[ $# == 3 ]]
then scp "$1" "scp://$3@$2/"
else
scp -i "$4" "$1" "scp://$3@$2/"
fi
