#!/usr/bin/env bash
# installs nginx
sudo apt-get update
sudo apt-get -y install nginx
config='
server {
        listen 80;
        listen [::]:80;

        root /var/www/alx-1/html;
        index index.html index.htm index.nginx-debian.html;

        # server_name jeremy.com www.example.com;

        location / {
                try_files $uri $uri/ =404;
        }
}
'
html='Hello World!'
