#!/usr/bin/env bash
# installs nginx
sudo apt-get update
sudo apt-get -y install nginx
config="
server {
        listen 80;
        listen [::]:80;

        root /var/www/alx-1/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
		error_page 404 /404.html;
		rewrite ^/redirect_me / permanent;

        location / {
                try_files \$uri \$uri/ =404;
        }
		location = /404.html {
                root /var/www/alx-1/html;
                internal;
        }

}
"
html='Hello World!'
