#!/usr/bin/env bash
# installs nginx
sudo apt-get update
sudo apt-get -y install nginx
config="
server {
        listen 80;
        listen [::]:80;

        root /var/www/alx-1/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
		error_page 404 /404.html;
		rewrite ^/redirect_me / permanent;

        location / {
                try_files \$uri \$uri/ =404;
        }
}
"
html='Hello World!'
sudo mkdir -p /var/www/alx-1/html/
# sudo chown "$USER:$USER" /var/www/alx-1
sudo tee /var/www/alx-1/html/index.html <<< "$html" &> /dev/null

sudo tee /etc/nginx/sites-available/alx-1.com <<< "$config" &> /dev/null
sudo ln /etc/nginx/sites-available/alx-1.com /etc/nginx/sites-enabled/alx-1.com
sudo rm /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/alx-1/html/404.html

if pgrep nginx; then sudo nginx -s reload; else sudo nginx; fi
