#!/usr/bin/env bash
# manages a daemon

if [ "$#" -ne 2 ]; then
	echo 'Usage: manage_my_process {start|stop|restart}'
elif [ "$1" = "start" ]; then
	./manage_my_process &
	echo "$!" | sudo tee /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" = "stop" ]; then
	pkill -f "./manage_my_process"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]; then
	pkill -f "./manage_my_process"
	sudo rm /var/run/my_process.pid
	./manage_my_process  &
	echo "$!" | sudo tee /var/run/my_process.pid
	echo "manage_my_process restarted"
else echo 'Usage: manage_my_process {start|stop|restart}'
fi
