#!/usr/bin/env bash
while read -r line; do
	read -r -a cols <<< "$(cut --output-delimiter=' ' -d ':' -f 1- <<< "$line")"
	
	printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s INFO\n" "${cols[4]}" "${cols[3]}" "${cols[5]}" "${cols[6]}" "${cols[2]}" "${cols[1]}" "${cols[4]}"
done < /etc/passwd
