#!/usr/bin/env bash
# selects IP and HTTP status from an apache log file then sorts it
awk '
{
	logs[$1 " " $9] += 1;
}
END {
	PROCINFO["sorted_in"] = "@val_num_desc"
	for (i in logs)
		printf("    %3s %s\n", logs[i], i);

}
' < apache-access.log
