#!/usr/bin/env bash
# configures some ip
cp /etc/hosts ~/hosts.new

printf "\n127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com\n" > ~/hosts.nnew
cat ~/hosts.new >> ~/hosts.nnew
cp -f ~/hosts.nnew ~/hosts.new
cp -f ~/hosts.new /etc/hosts
